spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:4306/topease?useUnicode=yes&characterEncoding=utf-8&useSSL=no
    username: root
    password: mysqlpasswd